# Generated by Django 5.0.4 on 2024-05-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240501_2031'),
    ]

    operations = [
    ]
