# Generated by Django 5.0.4 on 2024-05-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240501_2038'),
    ]

    operations = [
    ]
